#!/bin/bash

install() {
  log::info "[$(timestamp)][package][$name] preparing ..."

  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # prepare vars
  local name="tmux"
  # files
  local tmp_file="$name.tar.gz"
  local bin_file="./${name}-${PACKAGE_CORE_VERSION#v}-${platform}-${arch}/$name"

  # prepare context
  cd $tmp_dir

  which tmux >>/dev/null
  if [ "$?" != "0" ]; then
    log::info "[$(timestamp)] install tmux core ..."
    pm install -yqq tmux
  fi

  local PROGRAM_NAME=tmux
  local TMUX_HOME=~/.tmux
  local DESTINATION=$TMUX_HOME/plugins/tpm
  local TMUX_CONF=~/.tmux.conf
  local TMUX_PLUGIN_MANAGE_URL="https://github.com/tmux-plugins/tpm.git"

  # # Backup
  # if [ -d "$TMUX_HOME" ]; then
  #   [[ ! -d ~/.backup ]] && mkdir ~/.backup
  #   if [ -f $TMUX_CONF ]; then
  #     echo "Backup Tmux Configure to $HOME/.backup ..."
  #     [[ ! -d $TMUX_HOME ]] && mkdir $TMUX_HOME
  #     mv $TMUX_CONF $TMUX_HOME

  #     tar -zcvf ~/.backup/tmux-$(date +%Y-%m-%d-at-%H-%M).tgz $TMUX_HOME >>/dev/null 2>&1
  #   fi
  # fi

  # Clean
  if [ -d "$TMUX_HOME" ]; then
    log::info "[$(timestamp)] clean origin tmux to $HOME/.backup ..."
    rm -rf $TMUX_HOME >>/dev/null 2>&1
    rm -f $TMUX_CONF >>/dev/null 2>&1
  fi

  log::info "[$(timestamp)] download tmux plugin engine to $TMUX_HOME ..."
  os::git clone $TMUX_PLUGIN_MANAGE_URL $DESTINATION >>/dev/null

  log::info "[$(timestamp)] download tmux config ..."
  os::wget https://raw.githubusercontent.com/whatwewant/whatwewant.github.io/master/confs/tmux.conf -O $TMUX_CONF >>/dev/null

  # Reload TMUX environment so TPM is sourced:
  log::info "[$(timestamp)] reload tmux environment ..."
  # tmux source-file $TMUX_CONF
  #
  # Fix: https://stackoverflow.com/questions/41326985/tmux-no-server-running-on-private-tmp-tmux-502-default
  tmux start-server \; source-file $TMUX_CONF
}

export -f install
